steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/slideshow-backend:$COMMIT_SHA', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/slideshow-backend:$COMMIT_SHA']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'slideshow-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/slideshow-backend:$COMMIT_SHA'
      - '--region'
      - 'northamerica-northeast1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--max-instances'
      - '10'
      - '--timeout'
      - '300'
      - '--set-env-vars'
      - 'GCP_PROJECT=$PROJECT_ID,GCP_PROJECT_ID=$PROJECT_ID,GCP_REGION=northamerica-northeast1,CLOUD_TASKS_QUEUE=image-processing-queue,CLOUD_TASKS_LOCATION=northamerica-northeast1,WORKFLOW_URL=https://workflowexecutions.googleapis.com/v1/projects/crafty-router-207406/locations/northamerica-northeast1/workflows/trigger-image-job/executions,WORKFLOW_SERVICE_ACCOUNT=YOUR_SERVICE_ACCOUNT@crafty-router-207406.iam.gserviceaccount.com'

images:
  - 'gcr.io/$PROJECT_ID/slideshow-backend:$COMMIT_SHA'

options:
  machineType: 'N1_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
